package com.electronik54.revision_3.lombok.ch93_lombok_basics.solution;

/**
 * Solution for Challenge 93: Lombok Basics
 *
 * Demonstrates @Data, @Getter, @Setter, @NoArgsConstructor.
 */
public class Solution {

    public static void main(String[] args) {
        // @AllArgsConstructor (generated by @Data -> RequiredArgs + @NoArgs? Use explicit ctor via @Builder-like
        // @Data generates a constructor for final/@NonNull fields; for plain fields use @AllArgsConstructor.
        Person john = new Person("John", 30, "john@example.com");
        System.out.println(john);

        // Getter + setter from @Data
        john.setAge(31);
        System.out.println("Age after setter: " + john.getAge());

        // @NoArgsConstructor then setters
        Person copy1 = new Person("Alice", 25, "alice@example.com");
        Person copy2 = new Person("Alice", 25, "alice@example.com");
        System.out.println("Equals check (same values): " + copy1.equals(copy2));
    }
}